limit_req_zone $binary_remote_addr zone=mailit:10m rate=5r/m;

server {
    listen 5686;

    location / {
        limit_req zone=mailit burst=3 nodelay;
        limit_req_status 429;

        proxy_pass http://mail-it:5686;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin $http_origin;
    }
}
